linters-settings:
  openapi:
    exclude-rules:
      enum:
        - "spec.versions[0].schema.openAPIV3Schema.properties.spec.properties.sts.properties.provider"
        - "spec.versions[0].schema.openAPIV3Schema.properties.spec.properties.provider"
        - "spec.versions[0].schema.openAPIV3Schema.properties.spec.properties.upgrade.properties.remediation.properties.strategy.properties"
        - "spec.versions[0].schema.openAPIV3Schema.properties.spec.properties.uninstall.properties.deletionPropagation"
        - "spec.versions[0].schema.openAPIV3Schema.properties.spec.properties.driftDetection.properties.mode"
        - "spec.versions[0].schema.openAPIV3Schema.properties.spec.properties.upgrade.properties.remediation.properties.strategy"
        - "spec.versions[0].schema.openAPIV3Schema.properties.spec.properties.chart.properties.spec.properties.verify.properties.provider"
        - "spec.versions[0].schema.openAPIV3Schema.properties.status.properties.lastAttemptedReleaseAction"
        - "spec.versions[0].schema.openAPIV3Schema.properties.spec.properties.upgrade.properties.serverSideApply"
        - "spec.versions[0].schema.openAPIV3Schema.properties.spec.properties.rollback.properties.serverSideApply"
        - "spec.versions[0].schema.openAPIV3Schema.properties.spec.properties.waitStrategy.properties.name"
        - "spec.versions[0].schema.openAPIV3Schema.properties.spec.properties.postRenderStrategy"
        - "properties.logLevel"
        - "properties.logFormat"
  rbac:
    exclude-rules:
      wildcards:
        - kind: ClusterRole
          name: d8:operator-helm:helm-controller
