---
apiVersion: v1
kind: Service
metadata:
  name: operator-helm-controller
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "operator-helm-controller")) | nindent 2 }}
spec:
  ports:
    - name: admission-webhook
      port: 443
      targetPort: controller
      protocol: TCP
    - name: controller
      port: 9443
      targetPort: controller
      protocol: TCP
  selector:
    app: operator-helm-controller
