---
apiVersion: v1
kind: Secret
metadata:
  name: chart-values-controller-tls
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "chart-values-controller")) | nindent 2 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ .Values.operatorHelm.internal.chartValuesController.cert.ca | b64enc }}
  tls.crt: {{ .Values.operatorHelm.internal.chartValuesController.cert.crt | b64enc }}
  tls.key: {{ .Values.operatorHelm.internal.chartValuesController.cert.key | b64enc }}
