---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: helmclusteraddons.helm.deckhouse.io
spec:
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: |-
            HelmClusterAddon описывает Helm-релиз, управляемый на уровне кластера.

            Helm-чарт может содержать CRD и другие cluster-wide-ресурсы, поэтому для создания HelmClusterAddon требуются права `ClusterAdmin`.
            Для одного Helm-чарта из определённого репозитория в кластере может существовать только один ресурс HelmClusterAddon.
          properties:
            spec:
              properties:
                chart:
                  properties:
                    helmClusterAddonChart:
                      description: |
                        Имя Helm-чарта для установки из указанного репозитория (например, `ingress-nginx` или `redis`).
                    helmClusterAddonRepository:
                      description: |
                        Имя ресурса HelmClusterAddonRepository.

                        Указанный репозиторий используется как источник Helm-чарта.
                    version:
                      description: Версия Helm-чарта для установки.
                maintenance:
                  description: |
                    Режим согласования ресурса.

                    При значении `NoResourceReconciliation` контроллер приостанавливает согласование управляемых ресурсов, что позволяет изменять их вручную без перезаписи изменений контроллером.
                    При пустом значении (`""`) используется стандартный режим согласования.
                namespace:
                  description: Неймспейс для развёртывания релиза аддона.
                values:
                  description: Пользовательские значения Helm-чарта.
            status:
              properties:
                conditions:
                  description: Условия, отражающие текущее состояние ресурса.
                  items:
                    properties:
                      lastTransitionTime:
                        description: |-
                          Время последнего изменения состояния условия.
                      message:
                        description: |-
                          Сообщение с дополнительной информацией о состоянии условия.
                      observedGeneration:
                        description: |-
                          Поколение ресурса, на основе которого сформировано состояние условия.
                      reason:
                        description: |-
                          Причина последнего изменения состояния условия.
                      status:
                        description: Состояние условия.
                      type:
                        description: Тип условия.
                lastAppliedChart:
                  description: Helm-чарт, использованный при последней установке или обновлении аддона.
                  properties:
                    helmClusterAddonChart:
                      description: Имя Helm-чарта.
                    helmClusterAddonRepository:
                      description: Имя ресурса HelmClusterAddonRepository.
                    version:
                      description: Версия Helm-чарта.
                lastAppliedValues:
                  description: Пользовательские значения Helm-чарта, использованные при последней установке или обновлении аддона.
                observedGeneration:
                  description: Последнее поколение ресурса, обработанное контроллером.
                lastForceReconcileTime:
                  description: |
                    Время обработки последнего запроса на принудительную реконсиляцию.

                    Значение поля указывает на то, что запрос был обработан, но не свидетельствует об успешном завершении реконсиляции.
                    Результат реконсиляции отображается в условии `Ready`.
