{{- if eq (include "operator-helm.enable_rbacv2" .) "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: d8:namespace-capability:{{ .Chart.Name }}:user
  annotations:
    en.meta.deckhouse.io/title: "Module {{ .Chart.Name }}: view"
    ru.meta.deckhouse.io/title: "Модуль {{ .Chart.Name }}: просмотр"
    en.meta.deckhouse.io/description: "Read-only access to {{ .Chart.Name }} applications and their chart catalog in a namespace."
    ru.meta.deckhouse.io/description: "Доступ только на чтение к приложениям модуля {{ .Chart.Name }} и их каталогу чартов в пространстве имён."
  {{- include "helm_lib_module_labels" (list . (dict "rbac.deckhouse.io/kind" "capability" "rbac.deckhouse.io/capability" (printf "namespace-capability.%s.user" .Chart.Name) "rbac.deckhouse.io/scope" "namespace" "rbac.deckhouse.io/aggregate-to-namespace-as" "user")) | nindent 2 }}
rules:
- apiGroups:
  - helm.deckhouse.io
  resources:
  - helmapplicationcharts
  - helmapplicationrepositories
  - helmapplications
  verbs:
  - get
  - list
  - watch
{{- end }}
