---
apiVersion: v1
kind: Namespace
metadata:
  {{- include "helm_lib_module_labels" (list . (dict "prometheus.deckhouse.io/rules-watcher-enabled" "true" "security.deckhouse.io/enable-security-policy-check" "true" "security.deckhouse.io/pod-policy" "restricted" "security.deckhouse.io/pod-policy-action" "deny")) | nindent 2 }}
  annotations:
    helm.sh/resource-policy: keep
    werf.io/ownership: anyone
  name: d8-{{ .Chart.Name }}
---
{{- include "helm_lib_kube_rbac_proxy_ca_certificate" (list . (printf "d8-%s"  .Chart.Name)) }}
