name: Lint

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]
  push:
    branches:
      - main
      - release-*

env:
  TASK_X_REMOTE_TASKFILES: 1

jobs:
  lint_dh:
    runs-on: [self-hosted, large]
    continue-on-error: true
    name: Lint DH
    steps:
      - uses: actions/checkout@v6
      - uses: deckhouse/modules-actions/lint@main
        env:
          DMT_METRICS_URL: ${{ secrets.DMT_METRICS_URL }}
          DMT_METRICS_TOKEN: ${{ secrets.DMT_METRICS_TOKEN }}
# waiting for golangci-lint for go 1.26
  # lint:
  #   runs-on: [self-hosted, large]
  #   name: Lint
  #   steps:
  #     - name: Set up Go ${{ vars.GO_VERSION }}
  #       uses: actions/setup-go@v6
  #       with:
  #         go-version: "${{ vars.GO_VERSION }}"

  #     - uses: actions/checkout@v6

  #     - name: Install Task
  #       uses: arduino/setup-task@v2
  #       with:
  #         repo-token: ${{ secrets.GITHUB_TOKEN }}
      
  #     - name: Install golangci-lint
  #       run: task --yes deps:install:golangci-lint

  #     - name: Run linters
  #       run: task --yes lint
